mock update
kysect/Recademy pull request #12
Opened 2020-01-07 18:30 UTC by riiji

DataLists - added list of GitHubLinks
PrimitiveGenerator - simpler code by list extension
TypesGenerator - Better funcs, list of GitHubLinks, removed bugs
Mocker - Better funcs, removed bugs
ListExtension - new extension to list, this method get a random element from a list

2020-01-07 19:00 UTC, FrediKats requested changes

2020-01-07 19:00 UTC, FrediKats commented on Mock/Generators/DataLists.cs
> +        };
Кажется, тут можно было просто список username'ов хранить, а в коде добавлять github...

2020-01-07 19:00 UTC, FrediKats commented on Mock/Generators/TypesGenerator.cs
> +                DateCreate = (DateTime)creationTime,
creationTime.Value

2020-01-07 19:00 UTC, FrediKats commented on Mock/Mocker.cs
> +
Лишний перенос)

2020-01-07 19:00 UTC, FrediKats commented on Mock/Mocker.cs
> +        private const int MaxSkillsForUser = 4;
Я бы вынес это в какой-то GenerationConfig

2020-01-07 19:00 UTC, InRedikaWB commented on Mock/Mocker.cs
>          private static readonly HashSet<string> HashSet = new HashSet<string>();
Это очень стремная штука. Предлагаю заранее сгенерировать все возможные скиллы, чтобы они точно были. Тогда не нужно будет проверять есть ли они. А если будут скиллы, которые нигде не юзаются - ну ой.

2020-01-07 19:20 UTC, riiji commented on Mock/Mocker.cs
>          private static readonly HashSet<string> HashSet = new HashSet<string>();
Немного не понял. Все скиллы сгенерированы уже заранее (первые 2 строчки метода Mock)
Здесь рандом используется для того чтобы у каждого сгенерированного пользователя было случайное количество скиллов, проектов итп

2020-01-07 19:26 UTC, riiji commented on Mock/Generators/DataLists.cs
> +        };
Ок, можно, достаточно не очевидная тема тк я копипастил вручную и получал сразу линки с github

2020-01-07 19:35 UTC, InRedikaWB commented on Mock/Mocker.cs
>          private static readonly HashSet<string> HashSet = new HashSet<string>();
Да бл, гитхаб чет упоролся и выделил немного нет.
Я про HashSet. Его... Скажем так, не должно быть тут, глобально. Это какой-то костыль.

2020-01-07 19:36 UTC, riiji commented on Mock/Mocker.cs
>          private static readonly HashSet<string> HashSet = new HashSet<string>();
Может ты имеешь ввиду hashset?

2020-01-07 19:39 UTC, riiji commented on Mock/Mocker.cs
>          private static readonly HashSet<string> HashSet = new HashSet<string>();
Ок, у меня есть идея как пофиксить этот костыль

2020-01-07 23:23 UTC, FrediKats requested changes

2020-01-07 23:23 UTC, InRedikaWB commented on Mock/Mocker.cs
> +            while ((skillName = list.GetRandomUniqueValue()) != default)
Выглядит немного кринж. Как на счет сделать хотя бы TryGet?  По аналогии с TryParse. Возможно, это будет смотреть чуть лучше.

2020-01-07 23:23 UTC, InRedikaWB commented on Mock/Utility/ListExtension.cs
> +        public static T GetRandomUniqueValue<T>(this List<T> list)
Сделай лучше на ListExt как говорил @hrrrrustic. Просто у тебя будет в контекстном меню для List<T> предлагаться то, что для него... Скажем так, не подходит. Не нужно обобщать до уровня, когда эти обобщения противоречат логике.

2020-01-07 23:23 UTC, InRedikaWB commented on Mock/Utility/ListExtension.cs
> +            Random random = new Random();
Лучше не создавать рандом на каждый раз. Сделай уже какой-то статик класс тип RandomProvider, запихни туда рандом и со всех мест его вызывай. Если ты не знаешь почему не стоит создавать - советую загуглить и почему про рандом, не будет лишним.

2020-01-07 23:23 UTC, InRedikaWB commented on Mock/Utility/ListExtension.cs
> +        }
Вот это выглядит очень больно и не понятно.

2020-01-07 23:30 UTC, riiji commented on Mock/Utility/ListExtension.cs
> +        public static T GetRandomUniqueValue<T>(this List<T> list)
по поводу этой штуки как бы да, может я не тем инструментом пользуюсь, если я сделаю на адаптере, то у меня будет там лежать непонятный list, который там вообще не в тему, я как бы хочу сделать так чтобы те данные, которые там хранятся, они были невидимыми, это можно как то реализовать?

2020-01-07 23:31 UTC, riiji commented on Mock/Mocker.cs
> +            while ((skillName = list.GetRandomUniqueValue()) != default)
ок

2020-01-07 23:31 UTC, riiji commented on Mock/Utility/ListExtension.cs
> +            Random random = new Random();
ок

2020-01-08 02:29 UTC, hrrrrustic commented on Mock/Utility/ListExtension.cs
> +        }
Да вроде понятно, но есть подозрения, что в одну строчку можно *табаюсь и пытаюсь вставить снегиря*

2020-01-08 02:49 UTC, FrediKats requested changes
Потерял "/", а так все ок. Ты же проверил, что это работает?)

2020-01-08 02:49 UTC, InRedikaWB commented on Mock/Generators/TypesGenerator.cs
> +                GithubLink = "https://github.com"+DataLists.GitHubUsernames.GetRandomValue(),
Кажется, потерял  "/" между доменом и юзернеймом

2020-01-08 11:58 UTC, riiji commented on Mock/Generators/TypesGenerator.cs
> +                GithubLink = "https://github.com"+DataLists.GitHubUsernames.GetRandomValue(),
Вроде как да, теперь все ок

2020-01-08 11:59 UTC, riiji commented on Mock/Utility/ListExtension.cs
> +        }
outdated

2020-01-08 11:59 UTC, riiji commented on Mock/Mocker.cs
> +        private const int MaxSkillsForUser = 4;
Вынесено

2020-01-08 11:59 UTC, riiji commented on Mock/Mocker.cs
> +
Убрал

2020-01-08 11:59 UTC, riiji commented on Mock/Generators/TypesGenerator.cs
> +                DateCreate = (DateTime)creationTime,
Сделал

2020-01-08 12:24 UTC, riiji commented
> А может хватит фармить коммиты по одной строчке?))))))))

хм...

2020-01-08 14:08 UTC, FrediKats approved these changes

2020-01-08 14:09 UTC, merged