mock bug fix
kysect/Recademy pull request #8
Opened 2019-11-03 17:39 UTC by riiji

Исправлен баг, когда в request и response мог быть пользователь, которого не сущетсвует

2019-11-03 17:49 UTC, FrediKats requested changes

2019-11-03 17:49 UTC, InRedikaWB commented on Mock/Program.cs
>              HashSet<string> a = new HashSet<string>();
Уже не хакатон, можно потратить 14  секунд времени и дать нормальные названия.

2019-11-03 17:49 UTC, InRedikaWB commented on Mock/Program.cs
> +            HashSet<string> b = new HashSet<string>();
Зачем объявлять переменную и инициализировать ее тут, если она дальще  опять инициализируется и используется только внутри for'а?

2019-11-03 17:49 UTC, InRedikaWB commented on Mock/Program.cs
>              int rndVal;
Аналогично. Старайся минимально выпосить данные из скоупа. Если перемнная нужн отолько внутри фора - оставь ее там. Потому что я вот сейчас читаю и даже не представляю зачем это.

2019-11-03 17:49 UTC, InRedikaWB commented on Mock/Program.cs
> +                    }
Выглядит так, будто ты написал одинаковый код для одного юзера, а потом для второго. Возможно стоит вынести в метод, который принимает user'а и выполняет это, чтобы не дублировать.

2019-11-04 23:55 UTC, hrrrrustic requested changes
Ну, если учитывать, что это просто фикс, _лишь бы оно начало работать_ - то окей конечно, но в целом тут бы капитально переписать. Ну для начала тут Фреди уже расписал

2020-01-07 13:14 UTC, closed without merging